AWSTemplateFormatVersion: 2010-09-09
Resources:
################## FRONT & BASE ##################
  BucketS3:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName : !Ref BucketName
      #NotificationConfiguration:
      #  LambdaConfigurations:
      #  - Event: 's3:ObjectCreated:*'
      #  - Filter: 
      #  - Function: !GetAtt LambdaFunctionPhoto.Arn
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
      - BucketS3
      - CloudFrontOriginIdentity
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}'
            Action: 's3:GetObject'
            Resource: 
              - !Sub "arn:aws:s3:::${BucketName}/*"
  Parameters:
  EnvironmentName:
    Type: String
    Default: dev
  BucketName:
    Type: String
    Default: photoeventdev
Outputs:
  BucketS3ARL:
    Description: Arn de bucketS3
    Value: !GetAtt BucketS3.Arn
  Domain:
    Description: URL del cloudFront Distribution
    Value: !GetAtt CloudFront.DomainName