AWSTemplateFormatVersion: 2010-09-09
Resources:
################## FRONT & BASE ##################
  BucketS3:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName : !Ref BucketName
      #NotificationConfiguration:
      #  LambdaConfigurations:
      #  - Event: 's3:ObjectCreated:*'
      #  - Filter: 
      #  - Function: !GetAtt LambdaFunctionPhoto.Arn
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
  BucketName:
    Type: String
    Default: photoeventdev
Outputs:
  Domain:
    Description: Arn de bucketS3
    Value: !GetAtt BucketS3.Arn